#!/bin/bash
export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7'
export CUDA_LAUNCH_BLOCKING=1
# nohup python3 -u main.py --mode train --model_path model --device 3 > train_0228.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 10 --search_entity_size 5 --predict_epoches 10 --death_epoches 3 --model_path model_param2 --device 2 > train_0301_param2.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 6 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 7 --batch_maxsize 70 --model_path model_param3 --device 3 > train_0302_param3.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 11 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param4 --learning_rate 1.5e-4 --margin 0.05 --device 0 > train_0302_param4.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param5 --learning_rate 1.5e-4 --margin 0.5 --dropout_rate 0 --dropout_GCN 0 --device 2 > train_0303_param5.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param6 --learning_rate 1.5e-4 --margin 0.3 --margin_global 0.5 --dropout_rate 0 --dropout_GCN 0 --device 3 > train_0303_param6.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param7 --learning_rate 2e-4 --margin 0.3 --margin_global 0.3 --dropout_rate 0 --dropout_GCN 0 --global_beta 0.6 --device 1 > train_0304_param7.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param8 --learning_rate 1.5e-4 --margin 0.01 --margin_global 0.2 --dropout_rate 0 --dropout_GCN 0 --global_beta 0.8 --device 0 > train_0304_param8.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 7 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 70 --model_path model_param9 --learning_rate 2e-4 --margin 0.02 --margin_global 0.2 --dropout_rate 0 --dropout_GCN 0 --global_beta 1.0 --device 3 > train_0305_param9.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 8 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 80 --model_path model_param12 --learning_rate 2e-4 --margin 0.02 --margin_global 0.2 --dropout_rate 0 --dropout_GCN 0 --global_beta 1.0 --device 3 > train_0312_param12_doublerelu.log 2>&1 &
# nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 8 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 80 --model_path model_param14 --learning_rate 2e-4 --margin 0.02 --margin_global 0.2 --dropout_rate 0 --dropout_GCN 0 --global_beta 0.6 --device 2 > train_0312_param14_multisamp+local.log 2>&1 &
nohup python3 -u main.py --mode train --search_ment_size 12 --search_entity_size 8 --predict_epoches 12 --death_epoches 3 --keep_p_e_m 6 --keep_ctx_ent 6 --search_ment_size 12 --n_sample 8 --batch_maxsize 80 --model_path model_param16 --learning_rate 2e-4 --margin 0.02 --margin_global 0.2 --dropout_rate 0 --dropout_GCN 0 --global_beta 0.6 --device 7 > train_0318_param16_singlesamp+local+singleGCN.log 2>&1 &